# Generated by Django 4.0.1 on 2022-02-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('shipping', models.IntegerField(default=0)),
                ('finalamount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Packed'), (3, 'shipped'), (4, 'out of delivery'), (5, 'Delivered')], default=1)),
                ('paymentstatus', models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1)),
                ('mode', models.IntegerField(choices=[(1, 'COD'), (2, 'Net Banking')], default=1)),
                ('time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('orderId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('paymentId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('paymentsignature', models.CharField(default=None, max_length=50, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
    ]
