# Generated by Django 4.0.1 on 2022-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_buyer_otp_seller_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='paymentsignature',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
