# Generated by Django 4.0.1 on 2022-06-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
