# Generated by Django 4.0.1 on 2022-06-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
